### PR TITLE
Fix for checking if we are soft deleting

### PR DESCRIPTION
**Pull request by manavo**
## Change Summary

Fix for checking if soft deleting is enabled or not.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by manavo** [comment]
Any chance of getting this merged as well, and then tagging a new release? @hi019 @jasonbosco

**Comment by hi019** [comment]
I'll tag a new release later today. I'll also merge the README PR around that time 👍

**Comment by hi019** [comment]
@manavo https://github.com/typesense/laravel-scout-typesense-driver/releases/tag/v5.0.0-rc2

**Comment by manavo** [comment]
Looking good so far! 👍

**Pull request merged**
